apiVersion: v1
kind: Service
metadata:
  name: ivolve-service
  namespace: ivolve
spec:
  selector:
    app: ivolve-app
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30085
